os: Visual Studio 2015
configuration:
  - Release
before_build:
  - nuget restore
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
artifacts:
  - path: obj\%CONFIGURATION%
    name: Acid Editor (%CONFIGURATION%)
    type: zip