version: 0.1.1{build}
build:
  verbosity: minimal
os: Visual Studio 2017
configuration:
  - Release
before_build:
  - nuget restore
install:
  - set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%
artifacts:
  - path: Acid.Editor\bin\$(configuration)
    name: Acid Editor ($(configuration))
deploy:
  provider: GitHub
  release: Acid Editor $(appveyor_build_version)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: '(placeholder)'
  artifact: Acid.Editor\bin\$(configuration)
  auth_token:
    secure: vIHxXgPGlmN2KWCj0DrAzPpVMTT3w2fxc1tQu5KS9OXTIzJG8LZNoXM7IenLZy/2
    draft: true
    force_update: true
    prerelease: false
  on:
    appveyor_repo_tag: true